# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/icon_rom/icon_rom.xci
# IP: The module: 'icon_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/icon_rom/icon_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icon_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/icon_rom/icon_rom.xci
# IP: The module: 'icon_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/icon_rom/icon_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icon_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
