# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a75tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Document/School/ece540/pfinal/pf-2/pf-2.cache/wt [current_project]
set_property parent.project_path H:/Document/School/ece540/pfinal/pf-2/pf-2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/ece540/pfinal/Labyrinth/accel/all_icons.coe
add_files H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/ece540/p2/p2_1/project_3/all_icons.coe
add_files -quiet H:/Document/School/ece540/pfinal/pf-2/pf-2.runs/icon_rom_synth_1/icon_rom.dcp
set_property used_in_implementation false [get_files H:/Document/School/ece540/pfinal/pf-2/pf-2.runs/icon_rom_synth_1/icon_rom.dcp]
add_files -quiet H:/Document/School/ece540/pfinal/pf-2/pf-2.runs/clk_wizard_synth_1/clk_wizard.dcp
set_property used_in_implementation false [get_files H:/Document/School/ece540/pfinal/pf-2/pf-2.runs/clk_wizard_synth_1/clk_wizard.dcp]
add_files -quiet H:/Document/School/ece540/pfinal/pf-2/pf-2.runs/Square_Root_synth_1/Square_Root.dcp
set_property used_in_implementation false [get_files H:/Document/School/ece540/pfinal/pf-2/pf-2.runs/Square_Root_synth_1/Square_Root.dcp]
read_verilog -library xil_defaultlib {
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/world_map.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/world_if.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/map.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/icon_rom/sim/icon_rom.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/icon_rom/icon_rom_stub.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/dtg.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/colorizer.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/kcpsm6.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/bot_pgm.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/vga_subsystem.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/sevensegment.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/nexys4_bot_if.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/icon.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/debounce.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/bot.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/proj2.v
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/nexys4fpga.v
}
read_vhdl -library xil_defaultlib {
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/SPI_If.vhd
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/icon_rom/synth/icon_rom.vhd
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/icon_rom/icon_rom_stub.vhdl
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/ADXL362Ctrl.vhd
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/AccelArithmetics.vhd
  H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/AccelerometerCtl.vhd
}
read_edif H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/imports/accel/world_map.ngc
read_xdc H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/constrs_1/imports/accel/nexys4fpga_withvideo.xdc
set_property used_in_implementation false [get_files H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/constrs_1/imports/accel/nexys4fpga_withvideo.xdc]

catch { write_hwdef -file Nexys4fpga.hwdef }
synth_design -top Nexys4fpga -part xc7a75tcsg324-1
write_checkpoint -noxdef Nexys4fpga.dcp
catch { report_utilization -file Nexys4fpga_utilization_synth.rpt -pb Nexys4fpga_utilization_synth.pb }
