# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard.xci
# IP: The module: 'clk_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: H:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard.xci
# IP: The module: 'clk_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: h:/Document/School/ece540/pfinal/pf-2/pf-2.srcs/sources_1/ip/clk_wizard/clk_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
